//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeVinhTu_0577.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        public int Id_Sach { get; set; }
        public string MaSach { get; set; }
        public string TenSach { get; set; }
        public string MaLoai { get; set; }
        public Nullable<System.DateTime> NgayXuatBan { get; set; }
    }
}
